<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10.0</LangVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ForguncyBin Condition="'$(ForguncyBin)' == ''">$(MSBuildProjectDirectory)\..\..\lib</ForguncyBin>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ForguncyServerApi.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
    <PackageReference Include="SqlSugar" Version="5.1.4.111" />
    <PackageReference Include="MySql.Data" Version="8.0.30" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Reflection.DispatchProxy" Version="4.7.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />
    <Reference Include="System.Net.Http" />
    <Compile Include="..\..\Compatibility\IsExternalInit.cs" Link="Compatibility\IsExternalInit.cs" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GrapeCity.Forguncy.ServerApi">
      <HintPath>$(ForguncyBin)\GrapeCity.Forguncy.ServerApi.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.IdentityModel.JsonWebTokens">
      <HintPath>$(ForguncyBin)\Microsoft.IdentityModel.JsonWebTokens.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.IdentityModel.Logging">
      <HintPath>$(ForguncyBin)\Microsoft.IdentityModel.Logging.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.IdentityModel.Tokens">
      <HintPath>$(ForguncyBin)\Microsoft.IdentityModel.Tokens.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.IdentityModel.Tokens.Jwt">
      <HintPath>$(ForguncyBin)\System.IdentityModel.Tokens.Jwt.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
