allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@weapp-tailwindcss/logger@2.0.1'
  - '@weapp-tailwindcss/postcss-calc@1.0.3'
  - '@weapp-tailwindcss/postcss@3.2.0'
  - '@weapp-tailwindcss/reset@0.1.2'
  - '@weapp-tailwindcss/shared@2.0.1'
  - tailwindcss-config@2.0.2
  - weapp-style-injector@1.0.2
  - weapp-tailwindcss@5.2.0
