// Generated by scripts/generate-industry-dictionary.mjs. Do not edit manually.

export interface IndustryLeaf {
  industryCode: string
  industryName: string
  pid: string
  label: string
}

export interface IndustryGroup {
  value: string
  label: string
  children: IndustryLeaf[]
}

export const INDUSTRY_GROUPS: readonly IndustryGroup[] = [
  {
    value: '181',
    label: '机织服装制造',
    children: [
      {
        industryCode: '1811',
        industryName: '运动机织服装制造',
        pid: '181',
        label: '运动机织服装制造（1811）',
      },
      {
        industryCode: '1819',
        industryName: '其他机织服装制造',
        pid: '181',
        label: '其他机织服装制造（1819）',
      },
    ],
  },
  {
    value: '182',
    label: '针织或钩针编织服装制造',
    children: [
      {
        industryCode: '1821',
        industryName: '运动休闲针织服装制造',
        pid: '182',
        label: '运动休闲针织服装制造（1821）',
      },
      {
        industryCode: '1829',
        industryName: '其他针织或钩针编织服装制造',
        pid: '182',
        label: '其他针织或钩针编织服装制造（1829）',
      },
    ],
  },
  {
    value: '183',
    label: '服饰制造',
    children: [
      {
        industryCode: '1830',
        industryName: '服饰制造',
        pid: '183',
        label: '服饰制造（1830）',
      },
    ],
  },
  {
    value: '191',
    label: '皮革鞣制加工',
    children: [
      {
        industryCode: '1910',
        industryName: '皮革鞣制加工',
        pid: '191',
        label: '皮革鞣制加工（1910）',
      },
    ],
  },
  {
    value: '192',
    label: '皮革制品制造',
    children: [
      {
        industryCode: '1921',
        industryName: '皮革服装制造',
        pid: '192',
        label: '皮革服装制造（1921）',
      },
      {
        industryCode: '1922',
        industryName: '皮箱、包（袋）制造',
        pid: '192',
        label: '皮箱、包（袋）制造（1922）',
      },
      {
        industryCode: '1923',
        industryName: '皮手套及皮装饰制品制造',
        pid: '192',
        label: '皮手套及皮装饰制品制造（1923）',
      },
      {
        industryCode: '1929',
        industryName: '其他皮革制品制造',
        pid: '192',
        label: '其他皮革制品制造（1929）',
      },
    ],
  },
  {
    value: '193',
    label: '毛皮鞣制及制品加工',
    children: [
      {
        industryCode: '1931',
        industryName: '毛皮鞣制加工',
        pid: '193',
        label: '毛皮鞣制加工（1931）',
      },
      {
        industryCode: '1932',
        industryName: '毛皮服装加工',
        pid: '193',
        label: '毛皮服装加工（1932）',
      },
      {
        industryCode: '1939',
        industryName: '其他毛皮制品加工',
        pid: '193',
        label: '其他毛皮制品加工（1939）',
      },
    ],
  },
  {
    value: '194',
    label: '羽毛(绒)加工及制品制造',
    children: [
      {
        industryCode: '1941',
        industryName: '羽毛（绒）加工',
        pid: '194',
        label: '羽毛（绒）加工（1941）',
      },
      {
        industryCode: '1942',
        industryName: '羽毛（绒）制品加工',
        pid: '194',
        label: '羽毛（绒）制品加工（1942）',
      },
    ],
  },
  {
    value: '195',
    label: '制鞋业',
    children: [
      {
        industryCode: '1951',
        industryName: '纺织面料鞋制造',
        pid: '195',
        label: '纺织面料鞋制造（1951）',
      },
      {
        industryCode: '1952',
        industryName: '皮鞋制造',
        pid: '195',
        label: '皮鞋制造（1952）',
      },
      {
        industryCode: '1953',
        industryName: '塑料鞋制造',
        pid: '195',
        label: '塑料鞋制造（1953）',
      },
      {
        industryCode: '1954',
        industryName: '橡胶鞋制造',
        pid: '195',
        label: '橡胶鞋制造（1954）',
      },
      {
        industryCode: '1959',
        industryName: '其他制鞋业',
        pid: '195',
        label: '其他制鞋业（1959）',
      },
    ],
  },
  {
    value: '201',
    label: '木材加工',
    children: [
      {
        industryCode: '2011',
        industryName: '锯材加工',
        pid: '201',
        label: '锯材加工（2011）',
      },
      {
        industryCode: '2012',
        industryName: '木片加工',
        pid: '201',
        label: '木片加工（2012）',
      },
      {
        industryCode: '2019',
        industryName: '其他木材加工',
        pid: '201',
        label: '其他木材加工（2019）',
      },
    ],
  },
  {
    value: '202',
    label: '人造板制造',
    children: [
      {
        industryCode: '2021',
        industryName: '胶合板制造',
        pid: '202',
        label: '胶合板制造（2021）',
      },
      {
        industryCode: '2022',
        industryName: '纤维板制造',
        pid: '202',
        label: '纤维板制造（2022）',
      },
      {
        industryCode: '2023',
        industryName: '刨花板制造',
        pid: '202',
        label: '刨花板制造（2023）',
      },
      {
        industryCode: '2029',
        industryName: '其他人造板制造',
        pid: '202',
        label: '其他人造板制造（2029）',
      },
    ],
  },
  {
    value: '203',
    label: '木质制品制造',
    children: [
      {
        industryCode: '2031',
        industryName: '建筑用木料及木材组件加工',
        pid: '203',
        label: '建筑用木料及木材组件加工（2031）',
      },
      {
        industryCode: '2032',
        industryName: '木门窗制造',
        pid: '203',
        label: '木门窗制造（2032）',
      },
      {
        industryCode: '2033',
        industryName: '木楼梯制造',
        pid: '203',
        label: '木楼梯制造（2033）',
      },
      {
        industryCode: '2034',
        industryName: '木地板制造',
        pid: '203',
        label: '木地板制造（2034）',
      },
      {
        industryCode: '2035',
        industryName: '木制容器制造',
        pid: '203',
        label: '木制容器制造（2035）',
      },
      {
        industryCode: '2039',
        industryName: '软木制品及其他木制品制造',
        pid: '203',
        label: '软木制品及其他木制品制造（2039）',
      },
    ],
  },
  {
    value: '204',
    label: '竹、藤、棕、草等制品制造',
    children: [
      {
        industryCode: '2041',
        industryName: '竹制品制造',
        pid: '204',
        label: '竹制品制造（2041）',
      },
      {
        industryCode: '2042',
        industryName: '藤制品制造',
        pid: '204',
        label: '藤制品制造（2042）',
      },
      {
        industryCode: '2043',
        industryName: '棕制品制造',
        pid: '204',
        label: '棕制品制造（2043）',
      },
      {
        industryCode: '2049',
        industryName: '草及其他制品制造',
        pid: '204',
        label: '草及其他制品制造（2049）',
      },
    ],
  },
  {
    value: '211',
    label: '木质家具制造',
    children: [
      {
        industryCode: '2110',
        industryName: '木质家具制造',
        pid: '211',
        label: '木质家具制造（2110）',
      },
    ],
  },
  {
    value: '212',
    label: '竹、藤家具制造',
    children: [
      {
        industryCode: '2120',
        industryName: '竹、藤家具制造',
        pid: '212',
        label: '竹、藤家具制造（2120）',
      },
    ],
  },
  {
    value: '213',
    label: '金属家具制造',
    children: [
      {
        industryCode: '2130',
        industryName: '金属家具制造',
        pid: '213',
        label: '金属家具制造（2130）',
      },
    ],
  },
  {
    value: '214',
    label: '塑料家具制造',
    children: [
      {
        industryCode: '2140',
        industryName: '塑料家具制造',
        pid: '214',
        label: '塑料家具制造（2140）',
      },
    ],
  },
  {
    value: '219',
    label: '其他家具制造',
    children: [
      {
        industryCode: '2190',
        industryName: '其他家具制造',
        pid: '219',
        label: '其他家具制造（2190）',
      },
    ],
  },
  {
    value: '221',
    label: '纸浆制造',
    children: [
      {
        industryCode: '2211',
        industryName: '木竹浆制造',
        pid: '221',
        label: '木竹浆制造（2211）',
      },
      {
        industryCode: '2212',
        industryName: '非木竹浆制造',
        pid: '221',
        label: '非木竹浆制造（2212）',
      },
    ],
  },
  {
    value: '222',
    label: '造纸',
    children: [
      {
        industryCode: '2221',
        industryName: '机制纸及纸板制造',
        pid: '222',
        label: '机制纸及纸板制造（2221）',
      },
      {
        industryCode: '2222',
        industryName: '手工纸制造',
        pid: '222',
        label: '手工纸制造（2222）',
      },
      {
        industryCode: '2223',
        industryName: '加工纸制造',
        pid: '222',
        label: '加工纸制造（2223）',
      },
    ],
  },
  {
    value: '223',
    label: '纸制品制造',
    children: [
      {
        industryCode: '2231',
        industryName: '纸和纸板容器制造',
        pid: '223',
        label: '纸和纸板容器制造（2231）',
      },
      {
        industryCode: '2239',
        industryName: '其他纸制品制造',
        pid: '223',
        label: '其他纸制品制造（2239）',
      },
    ],
  },
  {
    value: '231',
    label: '印刷',
    children: [
      {
        industryCode: '2311',
        industryName: '书、报刊印刷',
        pid: '231',
        label: '书、报刊印刷（2311）',
      },
      {
        industryCode: '2312',
        industryName: '本册印制',
        pid: '231',
        label: '本册印制（2312）',
      },
      {
        industryCode: '2319',
        industryName: '包装装潢及其他印刷',
        pid: '231',
        label: '包装装潢及其他印刷（2319）',
      },
    ],
  },
  {
    value: '232',
    label: '装订及印刷相关服务',
    children: [
      {
        industryCode: '2320',
        industryName: '装订及印刷相关服务',
        pid: '232',
        label: '装订及印刷相关服务（2320）',
      },
    ],
  },
  {
    value: '233',
    label: '记录媒介复制',
    children: [
      {
        industryCode: '2330',
        industryName: '记录媒介复制',
        pid: '233',
        label: '记录媒介复制（2330）',
      },
    ],
  },
  {
    value: '241',
    label: '文教办公用品制造',
    children: [
      {
        industryCode: '2411',
        industryName: '文具制造',
        pid: '241',
        label: '文具制造（2411）',
      },
      {
        industryCode: '2412',
        industryName: '笔的制造',
        pid: '241',
        label: '笔的制造（2412）',
      },
      {
        industryCode: '2413',
        industryName: '教学用模型及教具制造',
        pid: '241',
        label: '教学用模型及教具制造（2413）',
      },
      {
        industryCode: '2414',
        industryName: '墨水、墨汁制造',
        pid: '241',
        label: '墨水、墨汁制造（2414）',
      },
      {
        industryCode: '2419',
        industryName: '其他文教办公用品制造',
        pid: '241',
        label: '其他文教办公用品制造（2419）',
      },
    ],
  },
  {
    value: '242',
    label: '乐器制造',
    children: [
      {
        industryCode: '2421',
        industryName: '中乐器制造',
        pid: '242',
        label: '中乐器制造（2421）',
      },
      {
        industryCode: '2422',
        industryName: '西乐器制造',
        pid: '242',
        label: '西乐器制造（2422）',
      },
      {
        industryCode: '2423',
        industryName: '电子乐器制造',
        pid: '242',
        label: '电子乐器制造（2423）',
      },
      {
        industryCode: '2429',
        industryName: '其他乐器及零件制造',
        pid: '242',
        label: '其他乐器及零件制造（2429）',
      },
    ],
  },
  {
    value: '243',
    label: '工艺美术及礼仪用品制造',
    children: [
      {
        industryCode: '2431',
        industryName: '雕塑工艺品制造',
        pid: '243',
        label: '雕塑工艺品制造（2431）',
      },
      {
        industryCode: '2432',
        industryName: '金属工艺品制造',
        pid: '243',
        label: '金属工艺品制造（2432）',
      },
      {
        industryCode: '2433',
        industryName: '漆器工艺品制造',
        pid: '243',
        label: '漆器工艺品制造（2433）',
      },
      {
        industryCode: '2434',
        industryName: '花画工艺品制造',
        pid: '243',
        label: '花画工艺品制造（2434）',
      },
      {
        industryCode: '2435',
        industryName: '天然植物纤维编织工艺品制造',
        pid: '243',
        label: '天然植物纤维编织工艺品制造（2435）',
      },
      {
        industryCode: '2436',
        industryName: '抽纱刺绣工艺品制造',
        pid: '243',
        label: '抽纱刺绣工艺品制造（2436）',
      },
      {
        industryCode: '2437',
        industryName: '地毯、挂毯制造',
        pid: '243',
        label: '地毯、挂毯制造（2437）',
      },
      {
        industryCode: '2438',
        industryName: '珠宝首饰及有关物品制造',
        pid: '243',
        label: '珠宝首饰及有关物品制造（2438）',
      },
      {
        industryCode: '2439',
        industryName: '其他工艺美术及礼仪用品制造',
        pid: '243',
        label: '其他工艺美术及礼仪用品制造（2439）',
      },
    ],
  },
  {
    value: '244',
    label: '体育用品制造',
    children: [
      {
        industryCode: '2441',
        industryName: '球类制造',
        pid: '244',
        label: '球类制造（2441）',
      },
      {
        industryCode: '2442',
        industryName: '专项运动器材及配件制造',
        pid: '244',
        label: '专项运动器材及配件制造（2442）',
      },
      {
        industryCode: '2443',
        industryName: '健身器材制造',
        pid: '244',
        label: '健身器材制造（2443）',
      },
      {
        industryCode: '2444',
        industryName: '运动防护用具制造',
        pid: '244',
        label: '运动防护用具制造（2444）',
      },
      {
        industryCode: '2449',
        industryName: '其他体育用品制造',
        pid: '244',
        label: '其他体育用品制造（2449）',
      },
    ],
  },
  {
    value: '245',
    label: '玩具制造',
    children: [
      {
        industryCode: '2451',
        industryName: '电玩具制造',
        pid: '245',
        label: '电玩具制造（2451）',
      },
      {
        industryCode: '2452',
        industryName: '塑胶玩具制造',
        pid: '245',
        label: '塑胶玩具制造（2452）',
      },
      {
        industryCode: '2453',
        industryName: '金属玩具制造 ',
        pid: '245',
        label: '金属玩具制造 （2453）',
      },
      {
        industryCode: '2454',
        industryName: '弹射玩具制造 ',
        pid: '245',
        label: '弹射玩具制造 （2454）',
      },
      {
        industryCode: '2455',
        industryName: '娃娃玩具制造',
        pid: '245',
        label: '娃娃玩具制造（2455）',
      },
      {
        industryCode: '2456',
        industryName: '儿童乘骑玩耍的童车类产品制造',
        pid: '245',
        label: '儿童乘骑玩耍的童车类产品制造（2456）',
      },
      {
        industryCode: '2459',
        industryName: '其他玩具制造',
        pid: '245',
        label: '其他玩具制造（2459）',
      },
    ],
  },
  {
    value: '246',
    label: '游艺器材及娱乐用品制造',
    children: [
      {
        industryCode: '2461',
        industryName: '露天游乐场所游乐设备制造',
        pid: '246',
        label: '露天游乐场所游乐设备制造（2461）',
      },
      {
        industryCode: '2462',
        industryName: '游艺用品及室内游艺器材制造',
        pid: '246',
        label: '游艺用品及室内游艺器材制造（2462）',
      },
      {
        industryCode: '2469',
        industryName: '其他娱乐用品制造',
        pid: '246',
        label: '其他娱乐用品制造（2469）',
      },
    ],
  },
  {
    value: '251',
    label: '精炼石油产品制造',
    children: [
      {
        industryCode: '2511',
        industryName: '原油加工及石油制品制造',
        pid: '251',
        label: '原油加工及石油制品制造（2511）',
      },
      {
        industryCode: '2519',
        industryName: '其他原油制造',
        pid: '251',
        label: '其他原油制造（2519）',
      },
    ],
  },
  {
    value: '252',
    label: '煤炭加工',
    children: [
      {
        industryCode: '2521',
        industryName: '炼焦',
        pid: '252',
        label: '炼焦（2521）',
      },
      {
        industryCode: '2522',
        industryName: '煤制合成气生产',
        pid: '252',
        label: '煤制合成气生产（2522）',
      },
      {
        industryCode: '2523',
        industryName: '煤制液体燃料生产',
        pid: '252',
        label: '煤制液体燃料生产（2523）',
      },
      {
        industryCode: '2524',
        industryName: '煤制品制造',
        pid: '252',
        label: '煤制品制造（2524）',
      },
      {
        industryCode: '2529',
        industryName: '其他煤炭加工',
        pid: '252',
        label: '其他煤炭加工（2529）',
      },
    ],
  },
  {
    value: '253',
    label: '核燃料加工',
    children: [
      {
        industryCode: '2530',
        industryName: '核燃料加工',
        pid: '253',
        label: '核燃料加工（2530）',
      },
    ],
  },
  {
    value: '254',
    label: '生物质燃料加工',
    children: [
      {
        industryCode: '2541',
        industryName: '生物质液体燃料生产',
        pid: '254',
        label: '生物质液体燃料生产（2541）',
      },
      {
        industryCode: '2542',
        industryName: '生物质致密成型燃料加工',
        pid: '254',
        label: '生物质致密成型燃料加工（2542）',
      },
    ],
  },
  {
    value: '261',
    label: '基础化学原料制造',
    children: [
      {
        industryCode: '2611',
        industryName: '无机酸制造',
        pid: '261',
        label: '无机酸制造（2611）',
      },
      {
        industryCode: '2612',
        industryName: '无机碱制造',
        pid: '261',
        label: '无机碱制造（2612）',
      },
      {
        industryCode: '2613',
        industryName: '无机盐制造',
        pid: '261',
        label: '无机盐制造（2613）',
      },
      {
        industryCode: '2614',
        industryName: '有机化学原料制造',
        pid: '261',
        label: '有机化学原料制造（2614）',
      },
      {
        industryCode: '2619',
        industryName: '其他基础化学原料制造',
        pid: '261',
        label: '其他基础化学原料制造（2619）',
      },
    ],
  },
  {
    value: '262',
    label: '肥料制造',
    children: [
      {
        industryCode: '2621',
        industryName: '氮肥制造',
        pid: '262',
        label: '氮肥制造（2621）',
      },
      {
        industryCode: '2622',
        industryName: '磷肥制造',
        pid: '262',
        label: '磷肥制造（2622）',
      },
      {
        industryCode: '2623',
        industryName: '钾肥制造',
        pid: '262',
        label: '钾肥制造（2623）',
      },
      {
        industryCode: '2624',
        industryName: '复混肥料制造',
        pid: '262',
        label: '复混肥料制造（2624）',
      },
      {
        industryCode: '2625',
        industryName: '有机肥料及微生物肥料制造',
        pid: '262',
        label: '有机肥料及微生物肥料制造（2625）',
      },
      {
        industryCode: '2629',
        industryName: '其他肥料制造',
        pid: '262',
        label: '其他肥料制造（2629）',
      },
    ],
  },
  {
    value: '263',
    label: '农药制造',
    children: [
      {
        industryCode: '2631',
        industryName: '化学农药制造',
        pid: '263',
        label: '化学农药制造（2631）',
      },
      {
        industryCode: '2632',
        industryName: '生物化学农药及微生物农药制造',
        pid: '263',
        label: '生物化学农药及微生物农药制造（2632）',
      },
    ],
  },
  {
    value: '264',
    label: '涂料、油墨、颜料及类似产品制造',
    children: [
      {
        industryCode: '2641',
        industryName: '涂料制造',
        pid: '264',
        label: '涂料制造（2641）',
      },
      {
        industryCode: '2642',
        industryName: '油墨及类似产品制造',
        pid: '264',
        label: '油墨及类似产品制造（2642）',
      },
      {
        industryCode: '2643',
        industryName: '工业颜料制造',
        pid: '264',
        label: '工业颜料制造（2643）',
      },
      {
        industryCode: '2644',
        industryName: '工艺美术颜料制造',
        pid: '264',
        label: '工艺美术颜料制造（2644）',
      },
      {
        industryCode: '2645',
        industryName: '染料制造',
        pid: '264',
        label: '染料制造（2645）',
      },
      {
        industryCode: '2646',
        industryName: '密封用填料及类似品制造',
        pid: '264',
        label: '密封用填料及类似品制造（2646）',
      },
    ],
  },
  {
    value: '265',
    label: '合成材料制造',
    children: [
      {
        industryCode: '2651',
        industryName: '初级形态塑料及合成树脂制造',
        pid: '265',
        label: '初级形态塑料及合成树脂制造（2651）',
      },
      {
        industryCode: '2652',
        industryName: '合成橡胶制造',
        pid: '265',
        label: '合成橡胶制造（2652）',
      },
      {
        industryCode: '2653',
        industryName: '合成纤维单（聚合）体制造',
        pid: '265',
        label: '合成纤维单（聚合）体制造（2653）',
      },
      {
        industryCode: '2659',
        industryName: '其他合成材料制造',
        pid: '265',
        label: '其他合成材料制造（2659）',
      },
    ],
  },
  {
    value: '266',
    label: '专用化学产品制造',
    children: [
      {
        industryCode: '2661',
        industryName: '化学试剂和助剂制造',
        pid: '266',
        label: '化学试剂和助剂制造（2661）',
      },
      {
        industryCode: '2662',
        industryName: '专项化学用品制造',
        pid: '266',
        label: '专项化学用品制造（2662）',
      },
      {
        industryCode: '2663',
        industryName: '林产化学产品制造',
        pid: '266',
        label: '林产化学产品制造（2663）',
      },
      {
        industryCode: '2664',
        industryName: '文化用信息化学品制造',
        pid: '266',
        label: '文化用信息化学品制造（2664）',
      },
      {
        industryCode: '2665',
        industryName: '医学生产用信息化学品制造',
        pid: '266',
        label: '医学生产用信息化学品制造（2665）',
      },
      {
        industryCode: '2666',
        industryName: '环境污染处理专用药剂材料制造',
        pid: '266',
        label: '环境污染处理专用药剂材料制造（2666）',
      },
      {
        industryCode: '2667',
        industryName: '动物胶制造',
        pid: '266',
        label: '动物胶制造（2667）',
      },
      {
        industryCode: '2669',
        industryName: '其他专用化学产品制造',
        pid: '266',
        label: '其他专用化学产品制造（2669）',
      },
    ],
  },
  {
    value: '267',
    label: '炸药、火工及焰火产品制造',
    children: [
      {
        industryCode: '2671',
        industryName: '炸药及火工产品制造',
        pid: '267',
        label: '炸药及火工产品制造（2671）',
      },
      {
        industryCode: '2672',
        industryName: '焰火、鞭炮产品制造',
        pid: '267',
        label: '焰火、鞭炮产品制造（2672）',
      },
    ],
  },
  {
    value: '268',
    label: '日用化学产品制造',
    children: [
      {
        industryCode: '2681',
        industryName: '肥皂及洗涤剂制造',
        pid: '268',
        label: '肥皂及洗涤剂制造（2681）',
      },
      {
        industryCode: '2682',
        industryName: '化妆品制造',
        pid: '268',
        label: '化妆品制造（2682）',
      },
      {
        industryCode: '2683',
        industryName: '口腔清洁用品制造',
        pid: '268',
        label: '口腔清洁用品制造（2683）',
      },
      {
        industryCode: '2684',
        industryName: '香料、香精制造',
        pid: '268',
        label: '香料、香精制造（2684）',
      },
      {
        industryCode: '2689',
        industryName: '其他日用化学产品制造',
        pid: '268',
        label: '其他日用化学产品制造（2689）',
      },
    ],
  },
  {
    value: '271',
    label: '化学药品原料药制造',
    children: [
      {
        industryCode: '2710',
        industryName: '化学药品原料药制造',
        pid: '271',
        label: '化学药品原料药制造（2710）',
      },
    ],
  },
  {
    value: '272',
    label: '化学药品制剂制造',
    children: [
      {
        industryCode: '2720',
        industryName: '化学药品制剂制造',
        pid: '272',
        label: '化学药品制剂制造（2720）',
      },
    ],
  },
  {
    value: '273',
    label: '中药饮片加工',
    children: [
      {
        industryCode: '2730',
        industryName: '中药饮片加工',
        pid: '273',
        label: '中药饮片加工（2730）',
      },
    ],
  },
  {
    value: '274',
    label: '中成药生产',
    children: [
      {
        industryCode: '2740',
        industryName: '中成药生产',
        pid: '274',
        label: '中成药生产（2740）',
      },
    ],
  },
  {
    value: '275',
    label: '兽用药品制造',
    children: [
      {
        industryCode: '2750',
        industryName: '兽用药品制造',
        pid: '275',
        label: '兽用药品制造（2750）',
      },
    ],
  },
  {
    value: '276',
    label: '生物药品制品制造',
    children: [
      {
        industryCode: '2761',
        industryName: '生物药品制造',
        pid: '276',
        label: '生物药品制造（2761）',
      },
      {
        industryCode: '2762',
        industryName: '基因工程药物和疫苗制造',
        pid: '276',
        label: '基因工程药物和疫苗制造（2762）',
      },
    ],
  },
  {
    value: '277',
    label: '卫生材料及医药用品制造',
    children: [
      {
        industryCode: '2770',
        industryName: '卫生材料及医药用品制造',
        pid: '277',
        label: '卫生材料及医药用品制造（2770）',
      },
    ],
  },
  {
    value: '278',
    label: '药用辅料及包装材料',
    children: [
      {
        industryCode: '2780',
        industryName: '药用辅料及包装材料',
        pid: '278',
        label: '药用辅料及包装材料（2780）',
      },
    ],
  },
  {
    value: '281',
    label: '纤维素纤维原料及纤维制造',
    children: [
      {
        industryCode: '2811',
        industryName: '化纤浆粕制造',
        pid: '281',
        label: '化纤浆粕制造（2811）',
      },
      {
        industryCode: '2812',
        industryName: '人造纤维（纤维素纤维）制造',
        pid: '281',
        label: '人造纤维（纤维素纤维）制造（2812）',
      },
    ],
  },
  {
    value: '282',
    label: '合成纤维制造',
    children: [
      {
        industryCode: '2821',
        industryName: '锦纶纤维制造',
        pid: '282',
        label: '锦纶纤维制造（2821）',
      },
      {
        industryCode: '2822',
        industryName: '涤纶纤维制造',
        pid: '282',
        label: '涤纶纤维制造（2822）',
      },
      {
        industryCode: '2823',
        industryName: '腈纶纤维制造',
        pid: '282',
        label: '腈纶纤维制造（2823）',
      },
      {
        industryCode: '2824',
        industryName: '维纶纤维制造',
        pid: '282',
        label: '维纶纤维制造（2824）',
      },
      {
        industryCode: '2825',
        industryName: '丙纶纤维制造',
        pid: '282',
        label: '丙纶纤维制造（2825）',
      },
      {
        industryCode: '2826',
        industryName: '氨纶纤维制造',
        pid: '282',
        label: '氨纶纤维制造（2826）',
      },
      {
        industryCode: '2829',
        industryName: '其他合成纤维制造',
        pid: '282',
        label: '其他合成纤维制造（2829）',
      },
    ],
  },
  {
    value: '283',
    label: '生物基材料制造',
    children: [
      {
        industryCode: '2831',
        industryName: '生物基化学纤维制造',
        pid: '283',
        label: '生物基化学纤维制造（2831）',
      },
      {
        industryCode: '2832',
        industryName: '生物基、淀粉基新材料制造',
        pid: '283',
        label: '生物基、淀粉基新材料制造（2832）',
      },
    ],
  },
  {
    value: '291',
    label: '橡胶制品业',
    children: [
      {
        industryCode: '2911',
        industryName: '轮胎制造',
        pid: '291',
        label: '轮胎制造（2911）',
      },
      {
        industryCode: '2912',
        industryName: '橡胶板、管、带制造',
        pid: '291',
        label: '橡胶板、管、带制造（2912）',
      },
      {
        industryCode: '2913',
        industryName: '橡胶零件制造',
        pid: '291',
        label: '橡胶零件制造（2913）',
      },
      {
        industryCode: '2914',
        industryName: '再生橡胶制造',
        pid: '291',
        label: '再生橡胶制造（2914）',
      },
      {
        industryCode: '2915',
        industryName: '日用及医用橡胶制品制造',
        pid: '291',
        label: '日用及医用橡胶制品制造（2915）',
      },
      {
        industryCode: '2916',
        industryName: '运动场地用塑胶制造',
        pid: '291',
        label: '运动场地用塑胶制造（2916）',
      },
      {
        industryCode: '2919',
        industryName: '其他橡胶制品制造',
        pid: '291',
        label: '其他橡胶制品制造（2919）',
      },
    ],
  },
  {
    value: '292',
    label: '塑料制品业',
    children: [
      {
        industryCode: '2921',
        industryName: '塑料薄膜制造',
        pid: '292',
        label: '塑料薄膜制造（2921）',
      },
      {
        industryCode: '2922',
        industryName: '塑料板、管、型材制造',
        pid: '292',
        label: '塑料板、管、型材制造（2922）',
      },
      {
        industryCode: '2923',
        industryName: '塑料丝、绳及编织品制造',
        pid: '292',
        label: '塑料丝、绳及编织品制造（2923）',
      },
      {
        industryCode: '2924',
        industryName: '泡沫塑料制造',
        pid: '292',
        label: '泡沫塑料制造（2924）',
      },
      {
        industryCode: '2925',
        industryName: '塑料人造革、合成革制造',
        pid: '292',
        label: '塑料人造革、合成革制造（2925）',
      },
      {
        industryCode: '2926',
        industryName: '塑料包装箱及容器制造',
        pid: '292',
        label: '塑料包装箱及容器制造（2926）',
      },
      {
        industryCode: '2927',
        industryName: '日用塑料制品制造',
        pid: '292',
        label: '日用塑料制品制造（2927）',
      },
      {
        industryCode: '2928',
        industryName: '人造草坪制造',
        pid: '292',
        label: '人造草坪制造（2928）',
      },
      {
        industryCode: '2929',
        industryName: '塑料零件及其他塑料制品制造',
        pid: '292',
        label: '塑料零件及其他塑料制品制造（2929）',
      },
    ],
  },
  {
    value: '301',
    label: '水泥、石灰和石膏制造',
    children: [
      {
        industryCode: '3011',
        industryName: '水泥制造',
        pid: '301',
        label: '水泥制造（3011）',
      },
      {
        industryCode: '3012',
        industryName: '石灰和石膏制造',
        pid: '301',
        label: '石灰和石膏制造（3012）',
      },
    ],
  },
  {
    value: '302',
    label: '石膏、水泥制品及类似制品制造',
    children: [
      {
        industryCode: '3021',
        industryName: '水泥制品制造',
        pid: '302',
        label: '水泥制品制造（3021）',
      },
      {
        industryCode: '3022',
        industryName: '砼结构构件制造',
        pid: '302',
        label: '砼结构构件制造（3022）',
      },
      {
        industryCode: '3023',
        industryName: '石棉水泥制品制造',
        pid: '302',
        label: '石棉水泥制品制造（3023）',
      },
      {
        industryCode: '3024',
        industryName: '轻质建筑材料制造',
        pid: '302',
        label: '轻质建筑材料制造（3024）',
      },
      {
        industryCode: '3029',
        industryName: '其他水泥类似制品制造',
        pid: '302',
        label: '其他水泥类似制品制造（3029）',
      },
    ],
  },
  {
    value: '303',
    label: '砖瓦、石材等建筑材料制造',
    children: [
      {
        industryCode: '3031',
        industryName: '粘土砖瓦及建筑砌块制造',
        pid: '303',
        label: '粘土砖瓦及建筑砌块制造（3031）',
      },
      {
        industryCode: '3032',
        industryName: '建筑用石加工',
        pid: '303',
        label: '建筑用石加工（3032）',
      },
      {
        industryCode: '3033',
        industryName: '防水建筑材料制造',
        pid: '303',
        label: '防水建筑材料制造（3033）',
      },
      {
        industryCode: '3034',
        industryName: '隔热和隔音材料制造',
        pid: '303',
        label: '隔热和隔音材料制造（3034）',
      },
      {
        industryCode: '3039',
        industryName: '其他建筑材料制造',
        pid: '303',
        label: '其他建筑材料制造（3039）',
      },
    ],
  },
  {
    value: '304',
    label: '玻璃制造',
    children: [
      {
        industryCode: '3041',
        industryName: '平板玻璃制造',
        pid: '304',
        label: '平板玻璃制造（3041）',
      },
      {
        industryCode: '3042',
        industryName: '特种玻璃制造',
        pid: '304',
        label: '特种玻璃制造（3042）',
      },
      {
        industryCode: '3049',
        industryName: '其他玻璃制造',
        pid: '304',
        label: '其他玻璃制造（3049）',
      },
    ],
  },
  {
    value: '305',
    label: '玻璃制品制造',
    children: [
      {
        industryCode: '3051',
        industryName: '技术玻璃制品制造',
        pid: '305',
        label: '技术玻璃制品制造（3051）',
      },
      {
        industryCode: '3052',
        industryName: '光学玻璃制造',
        pid: '305',
        label: '光学玻璃制造（3052）',
      },
      {
        industryCode: '3053',
        industryName: '玻璃仪器制造',
        pid: '305',
        label: '玻璃仪器制造（3053）',
      },
      {
        industryCode: '3054',
        industryName: '日用玻璃制品制造',
        pid: '305',
        label: '日用玻璃制品制造（3054）',
      },
      {
        industryCode: '3055',
        industryName: '玻璃包装容器制造',
        pid: '305',
        label: '玻璃包装容器制造（3055）',
      },
      {
        industryCode: '3056',
        industryName: '玻璃保温容器制造',
        pid: '305',
        label: '玻璃保温容器制造（3056）',
      },
      {
        industryCode: '3057',
        industryName: '制镜及类似品加工',
        pid: '305',
        label: '制镜及类似品加工（3057）',
      },
      {
        industryCode: '3059',
        industryName: '其他玻璃制品制造',
        pid: '305',
        label: '其他玻璃制品制造（3059）',
      },
    ],
  },
  {
    value: '306',
    label: '玻璃纤维和玻璃纤维增强塑料制品制造',
    children: [
      {
        industryCode: '3061',
        industryName: '玻璃纤维及制品制造',
        pid: '306',
        label: '玻璃纤维及制品制造（3061）',
      },
      {
        industryCode: '3062',
        industryName: '玻璃纤维增强塑料制品制造',
        pid: '306',
        label: '玻璃纤维增强塑料制品制造（3062）',
      },
    ],
  },
  {
    value: '307',
    label: '陶瓷制品制造',
    children: [
      {
        industryCode: '3071',
        industryName: '建筑陶瓷制品制造',
        pid: '307',
        label: '建筑陶瓷制品制造（3071）',
      },
      {
        industryCode: '3072',
        industryName: '卫生陶瓷制品制造',
        pid: '307',
        label: '卫生陶瓷制品制造（3072）',
      },
      {
        industryCode: '3073',
        industryName: '特种陶瓷制品制造',
        pid: '307',
        label: '特种陶瓷制品制造（3073）',
      },
      {
        industryCode: '3074',
        industryName: '日用陶瓷制品制造',
        pid: '307',
        label: '日用陶瓷制品制造（3074）',
      },
      {
        industryCode: '3075',
        industryName: '陈设艺术陶瓷制造',
        pid: '307',
        label: '陈设艺术陶瓷制造（3075）',
      },
      {
        industryCode: '3076',
        industryName: '园艺陶瓷制造',
        pid: '307',
        label: '园艺陶瓷制造（3076）',
      },
      {
        industryCode: '3079',
        industryName: '其他陶瓷制品制造',
        pid: '307',
        label: '其他陶瓷制品制造（3079）',
      },
    ],
  },
  {
    value: '308',
    label: '耐火材料制品制造',
    children: [
      {
        industryCode: '3081',
        industryName: '石棉制品制造',
        pid: '308',
        label: '石棉制品制造（3081）',
      },
      {
        industryCode: '3082',
        industryName: '云母制品制造',
        pid: '308',
        label: '云母制品制造（3082）',
      },
      {
        industryCode: '3089',
        industryName: '耐火陶瓷制品及其他耐火材料制造',
        pid: '308',
        label: '耐火陶瓷制品及其他耐火材料制造（3089）',
      },
    ],
  },
  {
    value: '309',
    label: '石墨及其他非金属矿物制品制造',
    children: [
      {
        industryCode: '3091',
        industryName: '石墨及碳素制品制造',
        pid: '309',
        label: '石墨及碳素制品制造（3091）',
      },
      {
        industryCode: '3099',
        industryName: '其他非金属矿物制品制造',
        pid: '309',
        label: '其他非金属矿物制品制造（3099）',
      },
    ],
  },
  {
    value: '311',
    label: '炼铁',
    children: [
      {
        industryCode: '3110',
        industryName: '炼铁',
        pid: '311',
        label: '炼铁（3110）',
      },
    ],
  },
  {
    value: '312',
    label: '炼钢',
    children: [
      {
        industryCode: '3120',
        industryName: '炼钢',
        pid: '312',
        label: '炼钢（3120）',
      },
    ],
  },
  {
    value: '313',
    label: '钢压延加工',
    children: [
      {
        industryCode: '3130',
        industryName: '钢压延加工',
        pid: '313',
        label: '钢压延加工（3130）',
      },
    ],
  },
  {
    value: '314',
    label: '铁合金冶炼',
    children: [
      {
        industryCode: '3140',
        industryName: '铁合金冶炼',
        pid: '314',
        label: '铁合金冶炼（3140）',
      },
    ],
  },
  {
    value: '321',
    label: '常用有色金属冶炼',
    children: [
      {
        industryCode: '3211',
        industryName: '铜冶炼',
        pid: '321',
        label: '铜冶炼（3211）',
      },
      {
        industryCode: '3212',
        industryName: '铅锌冶炼',
        pid: '321',
        label: '铅锌冶炼（3212）',
      },
      {
        industryCode: '3213',
        industryName: '镍钴冶炼',
        pid: '321',
        label: '镍钴冶炼（3213）',
      },
      {
        industryCode: '3214',
        industryName: '锡冶炼',
        pid: '321',
        label: '锡冶炼（3214）',
      },
      {
        industryCode: '3215',
        industryName: '锑冶炼',
        pid: '321',
        label: '锑冶炼（3215）',
      },
      {
        industryCode: '3216',
        industryName: '铝冶炼',
        pid: '321',
        label: '铝冶炼（3216）',
      },
      {
        industryCode: '3217',
        industryName: '镁冶炼',
        pid: '321',
        label: '镁冶炼（3217）',
      },
      {
        industryCode: '3218',
        industryName: '硅冶炼',
        pid: '321',
        label: '硅冶炼（3218）',
      },
      {
        industryCode: '3219',
        industryName: '其他常用有色金属冶炼',
        pid: '321',
        label: '其他常用有色金属冶炼（3219）',
      },
    ],
  },
  {
    value: '322',
    label: '贵金属冶炼',
    children: [
      {
        industryCode: '3221',
        industryName: '金冶炼',
        pid: '322',
        label: '金冶炼（3221）',
      },
      {
        industryCode: '3222',
        industryName: '银冶炼',
        pid: '322',
        label: '银冶炼（3222）',
      },
      {
        industryCode: '3229',
        industryName: '其他贵金属冶炼',
        pid: '322',
        label: '其他贵金属冶炼（3229）',
      },
    ],
  },
  {
    value: '323',
    label: '稀有稀土金属冶炼',
    children: [
      {
        industryCode: '3231',
        industryName: '钨钼冶炼',
        pid: '323',
        label: '钨钼冶炼（3231）',
      },
      {
        industryCode: '3232',
        industryName: '稀土金属冶炼',
        pid: '323',
        label: '稀土金属冶炼（3232）',
      },
      {
        industryCode: '3239',
        industryName: '其他稀有金属冶炼',
        pid: '323',
        label: '其他稀有金属冶炼（3239）',
      },
    ],
  },
  {
    value: '324',
    label: '有色金属合金制造',
    children: [
      {
        industryCode: '3240',
        industryName: '有色金属合金制造',
        pid: '324',
        label: '有色金属合金制造（3240）',
      },
    ],
  },
  {
    value: '325',
    label: '有色金属压延加工',
    children: [
      {
        industryCode: '3251',
        industryName: '铜压延加工',
        pid: '325',
        label: '铜压延加工（3251）',
      },
      {
        industryCode: '3252',
        industryName: '铝压延加工',
        pid: '325',
        label: '铝压延加工（3252）',
      },
      {
        industryCode: '3253',
        industryName: '贵金属压延加工',
        pid: '325',
        label: '贵金属压延加工（3253）',
      },
      {
        industryCode: '3254',
        industryName: '稀有稀土金属压延加工',
        pid: '325',
        label: '稀有稀土金属压延加工（3254）',
      },
      {
        industryCode: '3259',
        industryName: '其他有色金属压延加工',
        pid: '325',
        label: '其他有色金属压延加工（3259）',
      },
    ],
  },
  {
    value: '331',
    label: '结构性金属制品制造',
    children: [
      {
        industryCode: '3311',
        industryName: '金属结构制造',
        pid: '331',
        label: '金属结构制造（3311）',
      },
      {
        industryCode: '3312',
        industryName: '金属门窗制造',
        pid: '331',
        label: '金属门窗制造（3312）',
      },
    ],
  },
  {
    value: '332',
    label: '金属工具制造',
    children: [
      {
        industryCode: '3321',
        industryName: '切削工具制造',
        pid: '332',
        label: '切削工具制造（3321）',
      },
      {
        industryCode: '3322',
        industryName: '手工具制造',
        pid: '332',
        label: '手工具制造（3322）',
      },
      {
        industryCode: '3323',
        industryName: '农用及园林用金属工具制造',
        pid: '332',
        label: '农用及园林用金属工具制造（3323）',
      },
      {
        industryCode: '3324',
        industryName: '刀剪及类似日用金属工具制造',
        pid: '332',
        label: '刀剪及类似日用金属工具制造（3324）',
      },
      {
        industryCode: '3329',
        industryName: '其他金属工具制造',
        pid: '332',
        label: '其他金属工具制造（3329）',
      },
    ],
  },
  {
    value: '333',
    label: '集装箱及金属包装容器制造',
    children: [
      {
        industryCode: '3331',
        industryName: '集装箱制造',
        pid: '333',
        label: '集装箱制造（3331）',
      },
      {
        industryCode: '3332',
        industryName: '金属压力容器制造',
        pid: '333',
        label: '金属压力容器制造（3332）',
      },
      {
        industryCode: '3333',
        industryName: '金属包装容器及材料制造',
        pid: '333',
        label: '金属包装容器及材料制造（3333）',
      },
    ],
  },
  {
    value: '334',
    label: '金属丝绳及其制品制造',
    children: [
      {
        industryCode: '3340',
        industryName: '金属丝绳及其制品制造',
        pid: '334',
        label: '金属丝绳及其制品制造（3340）',
      },
    ],
  },
  {
    value: '335',
    label: '建筑、安全用金属制品制造',
    children: [
      {
        industryCode: '3351',
        industryName: '建筑、家具用金属配件制造',
        pid: '335',
        label: '建筑、家具用金属配件制造（3351）',
      },
      {
        industryCode: '3352',
        industryName: '建筑装饰及水暖管道零件制造',
        pid: '335',
        label: '建筑装饰及水暖管道零件制造（3352）',
      },
      {
        industryCode: '3353',
        industryName: '安全、消防用金属制品制造',
        pid: '335',
        label: '安全、消防用金属制品制造（3353）',
      },
      {
        industryCode: '3359',
        industryName: '其他建筑、安全用金属制品制造',
        pid: '335',
        label: '其他建筑、安全用金属制品制造（3359）',
      },
    ],
  },
  {
    value: '336',
    label: '金属表面处理及热处理加工',
    children: [
      {
        industryCode: '3360',
        industryName: '金属表面处理及热处理加工',
        pid: '336',
        label: '金属表面处理及热处理加工（3360）',
      },
    ],
  },
  {
    value: '337',
    label: '搪瓷制品制造',
    children: [
      {
        industryCode: '3371',
        industryName: '生产专用搪瓷制品制造',
        pid: '337',
        label: '生产专用搪瓷制品制造（3371）',
      },
      {
        industryCode: '3372',
        industryName: '建筑装饰搪瓷制品制造',
        pid: '337',
        label: '建筑装饰搪瓷制品制造（3372）',
      },
      {
        industryCode: '3373',
        industryName: '搪瓷卫生洁具制造',
        pid: '337',
        label: '搪瓷卫生洁具制造（3373）',
      },
      {
        industryCode: '3379',
        industryName: '搪瓷日用品及其他搪瓷制品制造',
        pid: '337',
        label: '搪瓷日用品及其他搪瓷制品制造（3379）',
      },
    ],
  },
  {
    value: '338',
    label: '金属制日用品制造',
    children: [
      {
        industryCode: '3381',
        industryName: '金属制厨房用器具制造',
        pid: '338',
        label: '金属制厨房用器具制造（3381）',
      },
      {
        industryCode: '3382',
        industryName: '金属制餐具和器皿制造',
        pid: '338',
        label: '金属制餐具和器皿制造（3382）',
      },
      {
        industryCode: '3383',
        industryName: '金属制卫生器具制造',
        pid: '338',
        label: '金属制卫生器具制造（3383）',
      },
      {
        industryCode: '3389',
        industryName: '其他金属制日用品制造',
        pid: '338',
        label: '其他金属制日用品制造（3389）',
      },
    ],
  },
  {
    value: '339',
    label: '铸造及其他金属制品制造',
    children: [
      {
        industryCode: '3391',
        industryName: '黑色金属铸造',
        pid: '339',
        label: '黑色金属铸造（3391）',
      },
      {
        industryCode: '3392',
        industryName: '有色金属铸造',
        pid: '339',
        label: '有色金属铸造（3392）',
      },
      {
        industryCode: '3393',
        industryName: '锻件及粉末冶金制品制造',
        pid: '339',
        label: '锻件及粉末冶金制品制造（3393）',
      },
      {
        industryCode: '3394',
        industryName: '交通及公共管理用金属标牌制造',
        pid: '339',
        label: '交通及公共管理用金属标牌制造（3394）',
      },
      {
        industryCode: '3399',
        industryName: '其他未列明金属制品制造',
        pid: '339',
        label: '其他未列明金属制品制造（3399）',
      },
    ],
  },
  {
    value: '341',
    label: '锅炉及原动设备制造',
    children: [
      {
        industryCode: '3411',
        industryName: '锅炉及辅助设备制造',
        pid: '341',
        label: '锅炉及辅助设备制造（3411）',
      },
      {
        industryCode: '3412',
        industryName: '内燃机及配件制造',
        pid: '341',
        label: '内燃机及配件制造（3412）',
      },
      {
        industryCode: '3413',
        industryName: '汽轮机及辅机制造',
        pid: '341',
        label: '汽轮机及辅机制造（3413）',
      },
      {
        industryCode: '3414',
        industryName: '水轮机及辅机制造',
        pid: '341',
        label: '水轮机及辅机制造（3414）',
      },
      {
        industryCode: '3415',
        industryName: '风能原动设备制造',
        pid: '341',
        label: '风能原动设备制造（3415）',
      },
      {
        industryCode: '3419',
        industryName: '其他原动设备制造',
        pid: '341',
        label: '其他原动设备制造（3419）',
      },
    ],
  },
  {
    value: '342',
    label: '金属加工机械制造',
    children: [
      {
        industryCode: '3421',
        industryName: '金属切削机床制造',
        pid: '342',
        label: '金属切削机床制造（3421）',
      },
      {
        industryCode: '3422',
        industryName: '金属成形机床制造',
        pid: '342',
        label: '金属成形机床制造（3422）',
      },
      {
        industryCode: '3423',
        industryName: '铸造机械制造',
        pid: '342',
        label: '铸造机械制造（3423）',
      },
      {
        industryCode: '3424',
        industryName: '金属切割及焊接设备制造',
        pid: '342',
        label: '金属切割及焊接设备制造（3424）',
      },
      {
        industryCode: '3425',
        industryName: '机床功能部件及附件制造',
        pid: '342',
        label: '机床功能部件及附件制造（3425）',
      },
      {
        industryCode: '3429',
        industryName: '其他金属加工机械制造',
        pid: '342',
        label: '其他金属加工机械制造（3429）',
      },
    ],
  },
  {
    value: '343',
    label: '物料搬运设备制造',
    children: [
      {
        industryCode: '3431',
        industryName: '轻小型起重设备制造',
        pid: '343',
        label: '轻小型起重设备制造（3431）',
      },
      {
        industryCode: '3432',
        industryName: '生产专用起重机制造',
        pid: '343',
        label: '生产专用起重机制造（3432）',
      },
      {
        industryCode: '3433',
        industryName: '生产专用车辆制造',
        pid: '343',
        label: '生产专用车辆制造（3433）',
      },
      {
        industryCode: '3434',
        industryName: '连续搬运设备制造',
        pid: '343',
        label: '连续搬运设备制造（3434）',
      },
      {
        industryCode: '3435',
        industryName: '电梯、自动扶梯及升降机制造',
        pid: '343',
        label: '电梯、自动扶梯及升降机制造（3435）',
      },
      {
        industryCode: '3436',
        industryName: '客运索道制造',
        pid: '343',
        label: '客运索道制造（3436）',
      },
      {
        industryCode: '3437',
        industryName: '机械式停车设备制造',
        pid: '343',
        label: '机械式停车设备制造（3437）',
      },
      {
        industryCode: '3439',
        industryName: '其他物料搬运设备制造',
        pid: '343',
        label: '其他物料搬运设备制造（3439）',
      },
    ],
  },
  {
    value: '344',
    label: '泵、阀门、压缩机及类似机械制造',
    children: [
      {
        industryCode: '3441',
        industryName: '泵及真空设备制造',
        pid: '344',
        label: '泵及真空设备制造（3441）',
      },
      {
        industryCode: '3442',
        industryName: '气体压缩机械制造',
        pid: '344',
        label: '气体压缩机械制造（3442）',
      },
      {
        industryCode: '3443',
        industryName: '阀门和旋塞制造',
        pid: '344',
        label: '阀门和旋塞制造（3443）',
      },
      {
        industryCode: '3444',
        industryName: '液压动力机械及元件制造',
        pid: '344',
        label: '液压动力机械及元件制造（3444）',
      },
      {
        industryCode: '3445',
        industryName: '液力动力机械元件制造',
        pid: '344',
        label: '液力动力机械元件制造（3445）',
      },
      {
        industryCode: '3446',
        industryName: '气压动力机械及元件制造',
        pid: '344',
        label: '气压动力机械及元件制造（3446）',
      },
    ],
  },
  {
    value: '345',
    label: '轴承、齿轮和传动部件制造',
    children: [
      {
        industryCode: '3451',
        industryName: '滚动轴承制造',
        pid: '345',
        label: '滚动轴承制造（3451）',
      },
      {
        industryCode: '3452',
        industryName: '滑动轴承制造',
        pid: '345',
        label: '滑动轴承制造（3452）',
      },
      {
        industryCode: '3453',
        industryName: '齿轮及齿轮减、变速箱制造',
        pid: '345',
        label: '齿轮及齿轮减、变速箱制造（3453）',
      },
      {
        industryCode: '3459',
        industryName: '其他传动部件制造',
        pid: '345',
        label: '其他传动部件制造（3459）',
      },
    ],
  },
  {
    value: '346',
    label: '烘炉、风机、包装等设备制造',
    children: [
      {
        industryCode: '3461',
        industryName: '烘炉、熔炉及电炉制造',
        pid: '346',
        label: '烘炉、熔炉及电炉制造（3461）',
      },
      {
        industryCode: '3462',
        industryName: '风机、风扇制造',
        pid: '346',
        label: '风机、风扇制造（3462）',
      },
      {
        industryCode: '3463',
        industryName: '气体、液体分离及纯净设备制造',
        pid: '346',
        label: '气体、液体分离及纯净设备制造（3463）',
      },
      {
        industryCode: '3464',
        industryName: '制冷、空调设备制造',
        pid: '346',
        label: '制冷、空调设备制造（3464）',
      },
      {
        industryCode: '3465',
        industryName: '风动和电动工具制造',
        pid: '346',
        label: '风动和电动工具制造（3465）',
      },
      {
        industryCode: '3466',
        industryName: '喷枪及类似器具制造',
        pid: '346',
        label: '喷枪及类似器具制造（3466）',
      },
      {
        industryCode: '3467',
        industryName: '包装专用设备制造',
        pid: '346',
        label: '包装专用设备制造（3467）',
      },
    ],
  },
  {
    value: '347',
    label: '文化、办公用机械制造',
    children: [
      {
        industryCode: '3471',
        industryName: '电影机械制造',
        pid: '347',
        label: '电影机械制造（3471）',
      },
      {
        industryCode: '3472',
        industryName: '幻灯及投影设备制造',
        pid: '347',
        label: '幻灯及投影设备制造（3472）',
      },
      {
        industryCode: '3473',
        industryName: '照相机及器材制造',
        pid: '347',
        label: '照相机及器材制造（3473）',
      },
      {
        industryCode: '3474',
        industryName: '复印和胶印设备制造',
        pid: '347',
        label: '复印和胶印设备制造（3474）',
      },
      {
        industryCode: '3475',
        industryName: '计算器及货币专用设备制造',
        pid: '347',
        label: '计算器及货币专用设备制造（3475）',
      },
      {
        industryCode: '3479',
        industryName: '其他文化、办公用机械制造',
        pid: '347',
        label: '其他文化、办公用机械制造（3479）',
      },
    ],
  },
  {
    value: '348',
    label: '通用零部件制造',
    children: [
      {
        industryCode: '3481',
        industryName: '金属密封件制造',
        pid: '348',
        label: '金属密封件制造（3481）',
      },
      {
        industryCode: '3482',
        industryName: '紧固件制造',
        pid: '348',
        label: '紧固件制造（3482）',
      },
      {
        industryCode: '3483',
        industryName: '弹簧制造',
        pid: '348',
        label: '弹簧制造（3483）',
      },
      {
        industryCode: '3484',
        industryName: '机械零部件加工',
        pid: '348',
        label: '机械零部件加工（3484）',
      },
      {
        industryCode: '3489',
        industryName: '其他通用零部件制造',
        pid: '348',
        label: '其他通用零部件制造（3489）',
      },
    ],
  },
  {
    value: '349',
    label: '其他通用设备制造业',
    children: [
      {
        industryCode: '3491',
        industryName: '工业机器人制造',
        pid: '349',
        label: '工业机器人制造（3491）',
      },
      {
        industryCode: '3492',
        industryName: '特殊作业机器人制造',
        pid: '349',
        label: '特殊作业机器人制造（3492）',
      },
      {
        industryCode: '3493',
        industryName: '增材制造装备制造',
        pid: '349',
        label: '增材制造装备制造（3493）',
      },
      {
        industryCode: '3499',
        industryName: '其他未列明通用设备制造业',
        pid: '349',
        label: '其他未列明通用设备制造业（3499）',
      },
    ],
  },
  {
    value: '351',
    label: '采矿、冶金、建筑专用设备制造',
    children: [
      {
        industryCode: '3511',
        industryName: '矿山机械制造',
        pid: '351',
        label: '矿山机械制造（3511）',
      },
      {
        industryCode: '3512',
        industryName: '石油钻采专用设备制造',
        pid: '351',
        label: '石油钻采专用设备制造（3512）',
      },
      {
        industryCode: '3513',
        industryName: '深海石油钻探设备制造',
        pid: '351',
        label: '深海石油钻探设备制造（3513）',
      },
      {
        industryCode: '3514',
        industryName: '建筑工程用机械制造',
        pid: '351',
        label: '建筑工程用机械制造（3514）',
      },
      {
        industryCode: '3515',
        industryName: '建筑材料生产专用机械制造',
        pid: '351',
        label: '建筑材料生产专用机械制造（3515）',
      },
      {
        industryCode: '3516',
        industryName: '冶金专用设备制造',
        pid: '351',
        label: '冶金专用设备制造（3516）',
      },
      {
        industryCode: '3517',
        industryName: '隧道施工专用机械制造',
        pid: '351',
        label: '隧道施工专用机械制造（3517）',
      },
    ],
  },
  {
    value: '352',
    label: '化工、木材、非金属加工专用设备制造',
    children: [
      {
        industryCode: '3521',
        industryName: '炼油、化工生产专用设备制造',
        pid: '352',
        label: '炼油、化工生产专用设备制造（3521）',
      },
      {
        industryCode: '3522',
        industryName: '橡胶加工专用设备制造',
        pid: '352',
        label: '橡胶加工专用设备制造（3522）',
      },
      {
        industryCode: '3523',
        industryName: '塑料加工专用设备制造',
        pid: '352',
        label: '塑料加工专用设备制造（3523）',
      },
      {
        industryCode: '3524',
        industryName: '木竹材加工机械制造',
        pid: '352',
        label: '木竹材加工机械制造（3524）',
      },
      {
        industryCode: '3525',
        industryName: '模具制造',
        pid: '352',
        label: '模具制造（3525）',
      },
      {
        industryCode: '3529',
        industryName: '其他非金属加工专用设备制造',
        pid: '352',
        label: '其他非金属加工专用设备制造（3529）',
      },
    ],
  },
  {
    value: '353',
    label: '食品、饮料、烟草及饲料生产专用设备制造',
    children: [
      {
        industryCode: '3531',
        industryName: '食品、酒、饮料及茶生产专用设备制',
        pid: '353',
        label: '食品、酒、饮料及茶生产专用设备制（3531）',
      },
      {
        industryCode: '3532',
        industryName: '农副食品加工专用设备制造',
        pid: '353',
        label: '农副食品加工专用设备制造（3532）',
      },
      {
        industryCode: '3533',
        industryName: '烟草生产专用设备制造',
        pid: '353',
        label: '烟草生产专用设备制造（3533）',
      },
      {
        industryCode: '3534',
        industryName: '饲料生产专用设备制造',
        pid: '353',
        label: '饲料生产专用设备制造（3534）',
      },
    ],
  },
  {
    value: '354',
    label: '印刷、制药、日化及日用品生产专用设备制造',
    children: [
      {
        industryCode: '3541',
        industryName: '制浆和造纸专用设备制造',
        pid: '354',
        label: '制浆和造纸专用设备制造（3541）',
      },
      {
        industryCode: '3542',
        industryName: '印刷专用设备制造',
        pid: '354',
        label: '印刷专用设备制造（3542）',
      },
      {
        industryCode: '3543',
        industryName: '日用化工专用设备制造',
        pid: '354',
        label: '日用化工专用设备制造（3543）',
      },
      {
        industryCode: '3544',
        industryName: '制药专用设备制造',
        pid: '354',
        label: '制药专用设备制造（3544）',
      },
      {
        industryCode: '3545',
        industryName: '照明器具生产专用设备制造',
        pid: '354',
        label: '照明器具生产专用设备制造（3545）',
      },
      {
        industryCode: '3546',
        industryName: '玻璃、陶瓷和搪瓷制品生产专用设备制造',
        pid: '354',
        label: '玻璃、陶瓷和搪瓷制品生产专用设备制造（3546）',
      },
      {
        industryCode: '3549',
        industryName: '其他日用品生产专用设备制造',
        pid: '354',
        label: '其他日用品生产专用设备制造（3549）',
      },
    ],
  },
  {
    value: '355',
    label: '纺织、服装和皮革加工专用设备制造',
    children: [
      {
        industryCode: '3551',
        industryName: '纺织专用设备制造',
        pid: '355',
        label: '纺织专用设备制造（3551）',
      },
      {
        industryCode: '3552',
        industryName: '皮革、毛皮及其制品加工专用设备制造',
        pid: '355',
        label: '皮革、毛皮及其制品加工专用设备制造（3552）',
      },
      {
        industryCode: '3553',
        industryName: '缝制机械制造',
        pid: '355',
        label: '缝制机械制造（3553）',
      },
      {
        industryCode: '3554',
        industryName: '洗涤机械制造',
        pid: '355',
        label: '洗涤机械制造（3554）',
      },
    ],
  },
  {
    value: '356',
    label: '电子和电工机械专用设备制造',
    children: [
      {
        industryCode: '3561',
        industryName: '电工机械专用设备制造',
        pid: '356',
        label: '电工机械专用设备制造（3561）',
      },
      {
        industryCode: '3562',
        industryName: '半导体器件专用设备制造',
        pid: '356',
        label: '半导体器件专用设备制造（3562）',
      },
      {
        industryCode: '3563',
        industryName: '电子元器件与机电组件设备制造',
        pid: '356',
        label: '电子元器件与机电组件设备制造（3563）',
      },
      {
        industryCode: '3569',
        industryName: '其他电子专用设备制造',
        pid: '356',
        label: '其他电子专用设备制造（3569）',
      },
    ],
  },
  {
    value: '357',
    label: '农、林、牧、渔专用机械制造',
    children: [
      {
        industryCode: '3571',
        industryName: '拖拉机制造',
        pid: '357',
        label: '拖拉机制造（3571）',
      },
      {
        industryCode: '3572',
        industryName: '机械化农业及园艺机具制造',
        pid: '357',
        label: '机械化农业及园艺机具制造（3572）',
      },
      {
        industryCode: '3573',
        industryName: '营林及木竹采伐机械制造',
        pid: '357',
        label: '营林及木竹采伐机械制造（3573）',
      },
      {
        industryCode: '3574',
        industryName: '畜牧机械制造',
        pid: '357',
        label: '畜牧机械制造（3574）',
      },
      {
        industryCode: '3575',
        industryName: '渔业机械制造',
        pid: '357',
        label: '渔业机械制造（3575）',
      },
      {
        industryCode: '3576',
        industryName: '农林牧渔机械配件制造',
        pid: '357',
        label: '农林牧渔机械配件制造（3576）',
      },
      {
        industryCode: '3577',
        industryName: '棉花加工机械制造',
        pid: '357',
        label: '棉花加工机械制造（3577）',
      },
      {
        industryCode: '3579',
        industryName: '其他农、林、牧、渔业机械制造',
        pid: '357',
        label: '其他农、林、牧、渔业机械制造（3579）',
      },
    ],
  },
  {
    value: '358',
    label: '医疗仪器设备及器械制造',
    children: [
      {
        industryCode: '3581',
        industryName: '医疗诊断、监护及治疗设备制造',
        pid: '358',
        label: '医疗诊断、监护及治疗设备制造（3581）',
      },
      {
        industryCode: '3582',
        industryName: '口腔科用设备及器具制造',
        pid: '358',
        label: '口腔科用设备及器具制造（3582）',
      },
      {
        industryCode: '3583',
        industryName: '医疗实验室及医用消毒设备和器具制造',
        pid: '358',
        label: '医疗实验室及医用消毒设备和器具制造（3583）',
      },
      {
        industryCode: '3584',
        industryName: '医疗、外科及兽医用器械制造',
        pid: '358',
        label: '医疗、外科及兽医用器械制造（3584）',
      },
      {
        industryCode: '3585',
        industryName: '机械治疗及病房护理设备制造',
        pid: '358',
        label: '机械治疗及病房护理设备制造（3585）',
      },
      {
        industryCode: '3586',
        industryName: '康复辅具制造',
        pid: '358',
        label: '康复辅具制造（3586）',
      },
      {
        industryCode: '3587',
        industryName: '眼镜制造',
        pid: '358',
        label: '眼镜制造（3587）',
      },
      {
        industryCode: '3589',
        industryName: '其他医疗设备及器械制造',
        pid: '358',
        label: '其他医疗设备及器械制造（3589）',
      },
    ],
  },
  {
    value: '359',
    label: '环保、邮政、社会公共服务及其他专用设备制造',
    children: [
      {
        industryCode: '3591',
        industryName: '环境保护专用设备制造',
        pid: '359',
        label: '环境保护专用设备制造（3591）',
      },
      {
        industryCode: '3592',
        industryName: '地质勘查专用设备制造',
        pid: '359',
        label: '地质勘查专用设备制造（3592）',
      },
      {
        industryCode: '3593',
        industryName: '邮政专用机械及器材制造',
        pid: '359',
        label: '邮政专用机械及器材制造（3593）',
      },
      {
        industryCode: '3594',
        industryName: '商业、饮食、服务专用设备制造',
        pid: '359',
        label: '商业、饮食、服务专用设备制造（3594）',
      },
      {
        industryCode: '3595',
        industryName: '社会公共安全设备及器材制造',
        pid: '359',
        label: '社会公共安全设备及器材制造（3595）',
      },
      {
        industryCode: '3596',
        industryName: '交通安全、管制及类似专用设备制造',
        pid: '359',
        label: '交通安全、管制及类似专用设备制造（3596）',
      },
      {
        industryCode: '3597',
        industryName: '水资源专用机械制造',
        pid: '359',
        label: '水资源专用机械制造（3597）',
      },
      {
        industryCode: '3599',
        industryName: '其他专用设备制造',
        pid: '359',
        label: '其他专用设备制造（3599）',
      },
    ],
  },
  {
    value: '361',
    label: '汽车整车制造',
    children: [
      {
        industryCode: '3611',
        industryName: '汽柴油车整车制造',
        pid: '361',
        label: '汽柴油车整车制造（3611）',
      },
      {
        industryCode: '3612',
        industryName: '新能源车整车制造',
        pid: '361',
        label: '新能源车整车制造（3612）',
      },
    ],
  },
  {
    value: '362',
    label: '汽车用发动机制造',
    children: [
      {
        industryCode: '3620',
        industryName: '汽车用发动机制造',
        pid: '362',
        label: '汽车用发动机制造（3620）',
      },
    ],
  },
  {
    value: '363',
    label: '改装汽车制造',
    children: [
      {
        industryCode: '3630',
        industryName: '改装汽车制造',
        pid: '363',
        label: '改装汽车制造（3630）',
      },
    ],
  },
  {
    value: '364',
    label: '低速汽车制造',
    children: [
      {
        industryCode: '3640',
        industryName: '低速汽车制造',
        pid: '364',
        label: '低速汽车制造（3640）',
      },
    ],
  },
  {
    value: '365',
    label: '电车制造',
    children: [
      {
        industryCode: '3650',
        industryName: '电车制造',
        pid: '365',
        label: '电车制造（3650）',
      },
    ],
  },
  {
    value: '366',
    label: '汽车车身、挂车制造',
    children: [
      {
        industryCode: '3660',
        industryName: '汽车车身、挂车制造',
        pid: '366',
        label: '汽车车身、挂车制造（3660）',
      },
    ],
  },
  {
    value: '367',
    label: '汽车零部件及配件制造',
    children: [
      {
        industryCode: '3670',
        industryName: '汽车零部件及配件制造',
        pid: '367',
        label: '汽车零部件及配件制造（3670）',
      },
    ],
  },
  {
    value: '371',
    label: '铁路运输设备制造',
    children: [
      {
        industryCode: '3711',
        industryName: '高铁车组制造',
        pid: '371',
        label: '高铁车组制造（3711）',
      },
      {
        industryCode: '3712',
        industryName: '铁路机车车辆制造',
        pid: '371',
        label: '铁路机车车辆制造（3712）',
      },
      {
        industryCode: '3713',
        industryName: '窄轨机车车辆制造',
        pid: '371',
        label: '窄轨机车车辆制造（3713）',
      },
      {
        industryCode: '3714',
        industryName: '高铁设备、配件制造',
        pid: '371',
        label: '高铁设备、配件制造（3714）',
      },
      {
        industryCode: '3715',
        industryName: '铁路机车车辆配件制造',
        pid: '371',
        label: '铁路机车车辆配件制造（3715）',
      },
      {
        industryCode: '3716',
        industryName: '铁路专用设备及器材、配件制造',
        pid: '371',
        label: '铁路专用设备及器材、配件制造（3716）',
      },
      {
        industryCode: '3719',
        industryName: '其他铁路运输设备制造',
        pid: '371',
        label: '其他铁路运输设备制造（3719）',
      },
    ],
  },
  {
    value: '372',
    label: '城市轨道交通设备制造',
    children: [
      {
        industryCode: '3720',
        industryName: '城市轨道交通设备制造',
        pid: '372',
        label: '城市轨道交通设备制造（3720）',
      },
    ],
  },
  {
    value: '373',
    label: '船舶及相关装置制造',
    children: [
      {
        industryCode: '3731',
        industryName: '金属船舶制造',
        pid: '373',
        label: '金属船舶制造（3731）',
      },
      {
        industryCode: '3732',
        industryName: '非金属船舶制造',
        pid: '373',
        label: '非金属船舶制造（3732）',
      },
      {
        industryCode: '3733',
        industryName: '娱乐船和运动船制造',
        pid: '373',
        label: '娱乐船和运动船制造（3733）',
      },
      {
        industryCode: '3734',
        industryName: '船用配套设备制造',
        pid: '373',
        label: '船用配套设备制造（3734）',
      },
      {
        industryCode: '3735',
        industryName: '船舶改装',
        pid: '373',
        label: '船舶改装（3735）',
      },
      {
        industryCode: '3736',
        industryName: '船舶拆除',
        pid: '373',
        label: '船舶拆除（3736）',
      },
      {
        industryCode: '3737',
        industryName: '海洋工程装备制造',
        pid: '373',
        label: '海洋工程装备制造（3737）',
      },
      {
        industryCode: '3739',
        industryName: '航标器材及其他相关装置制造',
        pid: '373',
        label: '航标器材及其他相关装置制造（3739）',
      },
    ],
  },
  {
    value: '374',
    label: '航空、航天器及设备制造',
    children: [
      {
        industryCode: '3741',
        industryName: '飞机制造',
        pid: '374',
        label: '飞机制造（3741）',
      },
      {
        industryCode: '3742',
        industryName: '航天器及运载火箭制造',
        pid: '374',
        label: '航天器及运载火箭制造（3742）',
      },
      {
        industryCode: '3743',
        industryName: '航天相关设备制造',
        pid: '374',
        label: '航天相关设备制造（3743）',
      },
      {
        industryCode: '3744',
        industryName: '航空相关设备制造',
        pid: '374',
        label: '航空相关设备制造（3744）',
      },
      {
        industryCode: '3749',
        industryName: '其他航空航天器制造',
        pid: '374',
        label: '其他航空航天器制造（3749）',
      },
    ],
  },
  {
    value: '375',
    label: '摩托车制造',
    children: [
      {
        industryCode: '3751',
        industryName: '摩托车整车制造',
        pid: '375',
        label: '摩托车整车制造（3751）',
      },
      {
        industryCode: '3752',
        industryName: '摩托车零部件及配件制造',
        pid: '375',
        label: '摩托车零部件及配件制造（3752）',
      },
    ],
  },
  {
    value: '376',
    label: '自行车和残疾人座车制造',
    children: [
      {
        industryCode: '3761',
        industryName: '自行车制造',
        pid: '376',
        label: '自行车制造（3761）',
      },
      {
        industryCode: '3762',
        industryName: '残疾人座车制造',
        pid: '376',
        label: '残疾人座车制造（3762）',
      },
    ],
  },
  {
    value: '377',
    label: '助动车制造',
    children: [
      {
        industryCode: '3770',
        industryName: '助动车制造',
        pid: '377',
        label: '助动车制造（3770）',
      },
    ],
  },
  {
    value: '378',
    label: '非公路休闲车及零配件制造',
    children: [
      {
        industryCode: '3780',
        industryName: '非公路休闲车及零配件制造',
        pid: '378',
        label: '非公路休闲车及零配件制造（3780）',
      },
    ],
  },
  {
    value: '379',
    label: '潜水救捞及其他未列明运输设备制造',
    children: [
      {
        industryCode: '3791',
        industryName: '潜水装备制造',
        pid: '379',
        label: '潜水装备制造（3791）',
      },
      {
        industryCode: '3792',
        industryName: '水下救捞装备制造',
        pid: '379',
        label: '水下救捞装备制造（3792）',
      },
      {
        industryCode: '3799',
        industryName: '其他未列明运输设备制造',
        pid: '379',
        label: '其他未列明运输设备制造（3799）',
      },
    ],
  },
  {
    value: '381',
    label: '电机制造',
    children: [
      {
        industryCode: '3811',
        industryName: '发电机及发电机组制造',
        pid: '381',
        label: '发电机及发电机组制造（3811）',
      },
      {
        industryCode: '3812',
        industryName: '电动机制造',
        pid: '381',
        label: '电动机制造（3812）',
      },
      {
        industryCode: '3813',
        industryName: '微特电机及组件制造',
        pid: '381',
        label: '微特电机及组件制造（3813）',
      },
      {
        industryCode: '3819',
        industryName: '其他电机制造',
        pid: '381',
        label: '其他电机制造（3819）',
      },
    ],
  },
  {
    value: '382',
    label: '输配电及控制设备制造',
    children: [
      {
        industryCode: '3821',
        industryName: '变压器、整流器和电感器制造',
        pid: '382',
        label: '变压器、整流器和电感器制造（3821）',
      },
      {
        industryCode: '3822',
        industryName: '电容器及其配套设备制造',
        pid: '382',
        label: '电容器及其配套设备制造（3822）',
      },
      {
        industryCode: '3824',
        industryName: '电力电子元器件制造',
        pid: '382',
        label: '电力电子元器件制造（3824）',
      },
      {
        industryCode: '3825',
        industryName: '光伏设备及元器件制造',
        pid: '382',
        label: '光伏设备及元器件制造（3825）',
      },
      {
        industryCode: '3829',
        industryName: '其他输配电及控制设备制造',
        pid: '382',
        label: '其他输配电及控制设备制造（3829）',
      },
    ],
  },
  {
    value: '383',
    label: '电线、电缆、光缆及电工器材制造',
    children: [
      {
        industryCode: '3831',
        industryName: '电线、电缆制造',
        pid: '383',
        label: '电线、电缆制造（3831）',
      },
      {
        industryCode: '3832',
        industryName: '光纤制造',
        pid: '383',
        label: '光纤制造（3832）',
      },
      {
        industryCode: '3833',
        industryName: '光缆制造',
        pid: '383',
        label: '光缆制造（3833）',
      },
      {
        industryCode: '3834',
        industryName: '绝缘制品制造',
        pid: '383',
        label: '绝缘制品制造（3834）',
      },
      {
        industryCode: '3839',
        industryName: '其他电工器材制造',
        pid: '383',
        label: '其他电工器材制造（3839）',
      },
    ],
  },
  {
    value: '384',
    label: '电池制造',
    children: [
      {
        industryCode: '3841',
        industryName: '锂离子电池制造',
        pid: '384',
        label: '锂离子电池制造（3841）',
      },
      {
        industryCode: '3842',
        industryName: '镍氢电池制造',
        pid: '384',
        label: '镍氢电池制造（3842）',
      },
      {
        industryCode: '3843',
        industryName: '铅蓄电池制造',
        pid: '384',
        label: '铅蓄电池制造（3843）',
      },
      {
        industryCode: '3844',
        industryName: '锌锰电池制造',
        pid: '384',
        label: '锌锰电池制造（3844）',
      },
      {
        industryCode: '3849',
        industryName: '其他电池制造',
        pid: '384',
        label: '其他电池制造（3849）',
      },
    ],
  },
  {
    value: '385',
    label: '家用电力器具制造',
    children: [
      {
        industryCode: '3851',
        industryName: '家用制冷电器具制造',
        pid: '385',
        label: '家用制冷电器具制造（3851）',
      },
      {
        industryCode: '3853',
        industryName: '家用通风电器具制造',
        pid: '385',
        label: '家用通风电器具制造（3853）',
      },
      {
        industryCode: '3854',
        industryName: '家用厨房电器具制造',
        pid: '385',
        label: '家用厨房电器具制造（3854）',
      },
      {
        industryCode: '3855',
        industryName: '家用清洁卫生电器具制造',
        pid: '385',
        label: '家用清洁卫生电器具制造（3855）',
      },
      {
        industryCode: '3856',
        industryName: '家用美容、保健护理电器具制造',
        pid: '385',
        label: '家用美容、保健护理电器具制造（3856）',
      },
      {
        industryCode: '3857',
        industryName: '家用电力器具专用配件制造',
        pid: '385',
        label: '家用电力器具专用配件制造（3857）',
      },
      {
        industryCode: '3859',
        industryName: '其他家用电力器具制造',
        pid: '385',
        label: '其他家用电力器具制造（3859）',
      },
    ],
  },
  {
    value: '386',
    label: '非电力家用器具制造',
    children: [
      {
        industryCode: '3861',
        industryName: '燃气及类似能源家用器具制造',
        pid: '386',
        label: '燃气及类似能源家用器具制造（3861）',
      },
      {
        industryCode: '3862',
        industryName: '太阳能器具制造',
        pid: '386',
        label: '太阳能器具制造（3862）',
      },
      {
        industryCode: '3869',
        industryName: '其他非电力家用器具制造',
        pid: '386',
        label: '其他非电力家用器具制造（3869）',
      },
    ],
  },
  {
    value: '387',
    label: '照明器具制造',
    children: [
      {
        industryCode: '3871',
        industryName: '电光源制造',
        pid: '387',
        label: '电光源制造（3871）',
      },
      {
        industryCode: '3872',
        industryName: '照明灯具制造',
        pid: '387',
        label: '照明灯具制造（3872）',
      },
      {
        industryCode: '3873',
        industryName: '舞台及场地用灯制造',
        pid: '387',
        label: '舞台及场地用灯制造（3873）',
      },
      {
        industryCode: '3874',
        industryName: '智能照明器具制造',
        pid: '387',
        label: '智能照明器具制造（3874）',
      },
      {
        industryCode: '3879',
        industryName: '灯用电器附件及其他照明器具制造',
        pid: '387',
        label: '灯用电器附件及其他照明器具制造（3879）',
      },
    ],
  },
  {
    value: '389',
    label: '其他电气机械及器材制造',
    children: [
      {
        industryCode: '3891',
        industryName: '电气信号设备装置制造',
        pid: '389',
        label: '电气信号设备装置制造（3891）',
      },
      {
        industryCode: '3899',
        industryName: '其他未列明电气机械及器材制造',
        pid: '389',
        label: '其他未列明电气机械及器材制造（3899）',
      },
    ],
  },
  {
    value: '391',
    label: '计算机制造',
    children: [
      {
        industryCode: '3911',
        industryName: '计算机整机制造',
        pid: '391',
        label: '计算机整机制造（3911）',
      },
      {
        industryCode: '3912',
        industryName: '计算机零部件制造',
        pid: '391',
        label: '计算机零部件制造（3912）',
      },
      {
        industryCode: '3913',
        industryName: '计算机外围设备制造',
        pid: '391',
        label: '计算机外围设备制造（3913）',
      },
      {
        industryCode: '3914',
        industryName: '工业控制计算机及系统制造',
        pid: '391',
        label: '工业控制计算机及系统制造（3914）',
      },
      {
        industryCode: '3915',
        industryName: '信息安全设备制造',
        pid: '391',
        label: '信息安全设备制造（3915）',
      },
    ],
  },
  {
    value: '392',
    label: '通信设备制造',
    children: [
      {
        industryCode: '3921',
        industryName: '通信系统设备制造',
        pid: '392',
        label: '通信系统设备制造（3921）',
      },
      {
        industryCode: '3922',
        industryName: '通信终端设备制造',
        pid: '392',
        label: '通信终端设备制造（3922）',
      },
    ],
  },
  {
    value: '393',
    label: '广播电视设备制造',
    children: [
      {
        industryCode: '3931',
        industryName: '广播电视节目制作及发射设备制造',
        pid: '393',
        label: '广播电视节目制作及发射设备制造（3931）',
      },
      {
        industryCode: '3932',
        industryName: '广播电视接收设备制造',
        pid: '393',
        label: '广播电视接收设备制造（3932）',
      },
      {
        industryCode: '3933',
        industryName: '广播电视专用配件制造',
        pid: '393',
        label: '广播电视专用配件制造（3933）',
      },
      {
        industryCode: '3934',
        industryName: '专业音响设备制造',
        pid: '393',
        label: '专业音响设备制造（3934）',
      },
      {
        industryCode: '3939',
        industryName: '应用电视设备及其他广播电视设备制造',
        pid: '393',
        label: '应用电视设备及其他广播电视设备制造（3939）',
      },
    ],
  },
  {
    value: '394',
    label: '雷达及配套设备制造',
    children: [
      {
        industryCode: '3940',
        industryName: '雷达及配套设备制造',
        pid: '394',
        label: '雷达及配套设备制造（3940）',
      },
    ],
  },
  {
    value: '395',
    label: '非专业视听设备制造',
    children: [
      {
        industryCode: '3951',
        industryName: '电视机制造',
        pid: '395',
        label: '电视机制造（3951）',
      },
      {
        industryCode: '3952',
        industryName: '音响设备制造',
        pid: '395',
        label: '音响设备制造（3952）',
      },
      {
        industryCode: '3953',
        industryName: '影视录放设备制造',
        pid: '395',
        label: '影视录放设备制造（3953）',
      },
    ],
  },
  {
    value: '396',
    label: '智能消费设备制造',
    children: [
      {
        industryCode: '3961',
        industryName: '可穿戴智能设备制造',
        pid: '396',
        label: '可穿戴智能设备制造（3961）',
      },
      {
        industryCode: '3962',
        industryName: '智能车载设备制造',
        pid: '396',
        label: '智能车载设备制造（3962）',
      },
      {
        industryCode: '3963',
        industryName: '智能无人飞行器制造',
        pid: '396',
        label: '智能无人飞行器制造（3963）',
      },
      {
        industryCode: '3964',
        industryName: '服务消费机器人制造',
        pid: '396',
        label: '服务消费机器人制造（3964）',
      },
      {
        industryCode: '3969',
        industryName: '其他智能消费设备制造',
        pid: '396',
        label: '其他智能消费设备制造（3969）',
      },
    ],
  },
  {
    value: '397',
    label: '电子器件制造',
    children: [
      {
        industryCode: '3971',
        industryName: '电子真空器件制造',
        pid: '397',
        label: '电子真空器件制造（3971）',
      },
      {
        industryCode: '3972',
        industryName: '半导体分立器件制造',
        pid: '397',
        label: '半导体分立器件制造（3972）',
      },
      {
        industryCode: '3973',
        industryName: '集成电路制造',
        pid: '397',
        label: '集成电路制造（3973）',
      },
      {
        industryCode: '3974',
        industryName: '显示器件制造',
        pid: '397',
        label: '显示器件制造（3974）',
      },
      {
        industryCode: '3975',
        industryName: '半导体照明器件制造',
        pid: '397',
        label: '半导体照明器件制造（3975）',
      },
      {
        industryCode: '3976',
        industryName: '光电子器件制造',
        pid: '397',
        label: '光电子器件制造（3976）',
      },
      {
        industryCode: '3979',
        industryName: '其他电子器件制造',
        pid: '397',
        label: '其他电子器件制造（3979）',
      },
    ],
  },
  {
    value: '398',
    label: '电子元件及电子专用材料制造',
    children: [
      {
        industryCode: '3981',
        industryName: '电阻电容电感元件制造',
        pid: '398',
        label: '电阻电容电感元件制造（3981）',
      },
      {
        industryCode: '3982',
        industryName: '电子电路制造',
        pid: '398',
        label: '电子电路制造（3982）',
      },
      {
        industryCode: '3983',
        industryName: '敏感元件及传感器制造',
        pid: '398',
        label: '敏感元件及传感器制造（3983）',
      },
      {
        industryCode: '3984',
        industryName: '电声器件及零件制造',
        pid: '398',
        label: '电声器件及零件制造（3984）',
      },
      {
        industryCode: '3985',
        industryName: '电子专用材料制造',
        pid: '398',
        label: '电子专用材料制造（3985）',
      },
      {
        industryCode: '3989',
        industryName: '其他电子元件制造',
        pid: '398',
        label: '其他电子元件制造（3989）',
      },
    ],
  },
  {
    value: '399',
    label: '其他电子设备制造',
    children: [
      {
        industryCode: '3990',
        industryName: '其他电子设备制造',
        pid: '399',
        label: '其他电子设备制造（3990）',
      },
    ],
  },
  {
    value: '401',
    label: '通用仪器仪表制造',
    children: [
      {
        industryCode: '4011',
        industryName: '工业自动控制系统装置制造',
        pid: '401',
        label: '工业自动控制系统装置制造（4011）',
      },
      {
        industryCode: '4012',
        industryName: '电工仪器仪表制造',
        pid: '401',
        label: '电工仪器仪表制造（4012）',
      },
      {
        industryCode: '4013',
        industryName: '绘图、计算及测量仪器制造',
        pid: '401',
        label: '绘图、计算及测量仪器制造（4013）',
      },
      {
        industryCode: '4014',
        industryName: '实验分析仪器制造',
        pid: '401',
        label: '实验分析仪器制造（4014）',
      },
      {
        industryCode: '4015',
        industryName: '试验机制造',
        pid: '401',
        label: '试验机制造（4015）',
      },
      {
        industryCode: '4016',
        industryName: '供应用仪器仪表制造',
        pid: '401',
        label: '供应用仪器仪表制造（4016）',
      },
      {
        industryCode: '4019',
        industryName: '其他通用仪器制造',
        pid: '401',
        label: '其他通用仪器制造（4019）',
      },
    ],
  },
  {
    value: '402',
    label: '专用仪器仪表制造',
    children: [
      {
        industryCode: '4021',
        industryName: '环境监测专用仪器仪表制造',
        pid: '402',
        label: '环境监测专用仪器仪表制造（4021）',
      },
      {
        industryCode: '4022',
        industryName: '运输设备及生产用计数仪表制造',
        pid: '402',
        label: '运输设备及生产用计数仪表制造（4022）',
      },
      {
        industryCode: '4023',
        industryName: '导航、测绘、气象及海洋专用仪器制造',
        pid: '402',
        label: '导航、测绘、气象及海洋专用仪器制造（4023）',
      },
      {
        industryCode: '4024',
        industryName: '农林牧渔专用仪器仪表制造',
        pid: '402',
        label: '农林牧渔专用仪器仪表制造（4024）',
      },
      {
        industryCode: '4025',
        industryName: '地质勘探和地震专用仪器制造',
        pid: '402',
        label: '地质勘探和地震专用仪器制造（4025）',
      },
      {
        industryCode: '4026',
        industryName: '教学专用仪器制造',
        pid: '402',
        label: '教学专用仪器制造（4026）',
      },
      {
        industryCode: '4027',
        industryName: '核子及核辐射测量仪器制造',
        pid: '402',
        label: '核子及核辐射测量仪器制造（4027）',
      },
      {
        industryCode: '4028',
        industryName: '电子测量仪器制造',
        pid: '402',
        label: '电子测量仪器制造（4028）',
      },
      {
        industryCode: '4029',
        industryName: '其他专用仪器制造',
        pid: '402',
        label: '其他专用仪器制造（4029）',
      },
    ],
  },
  {
    value: '403',
    label: '钟表与计时仪器制造',
    children: [
      {
        industryCode: '4030',
        industryName: '钟表与计时仪器制造',
        pid: '403',
        label: '钟表与计时仪器制造（4030）',
      },
    ],
  },
  {
    value: '404',
    label: '光学仪器制造',
    children: [
      {
        industryCode: '4040',
        industryName: '光学仪器制造',
        pid: '404',
        label: '光学仪器制造（4040）',
      },
    ],
  },
  {
    value: '405',
    label: '衡器制造',
    children: [
      {
        industryCode: '4050',
        industryName: '衡器制造',
        pid: '405',
        label: '衡器制造（4050）',
      },
    ],
  },
  {
    value: '409',
    label: '其他仪器仪表制造业',
    children: [
      {
        industryCode: '4090',
        industryName: '其他仪器仪表制造业',
        pid: '409',
        label: '其他仪器仪表制造业（4090）',
      },
    ],
  },
  {
    value: '411',
    label: '日用杂品制造',
    children: [
      {
        industryCode: '4111',
        industryName: '鬃毛加工、制刷及清扫工具制造',
        pid: '411',
        label: '鬃毛加工、制刷及清扫工具制造（4111）',
      },
      {
        industryCode: '4119',
        industryName: '其他日用杂品制造',
        pid: '411',
        label: '其他日用杂品制造（4119）',
      },
    ],
  },
  {
    value: '412',
    label: '核辐射加工',
    children: [
      {
        industryCode: '4120',
        industryName: '核辐射加工',
        pid: '412',
        label: '核辐射加工（4120）',
      },
    ],
  },
  {
    value: '419',
    label: '其他未列明制造业',
    children: [
      {
        industryCode: '4190',
        industryName: '其他未列明制造业',
        pid: '419',
        label: '其他未列明制造业（4190）',
      },
    ],
  },
  {
    value: '421',
    label: '金属废料和碎屑加工处理',
    children: [
      {
        industryCode: '4210',
        industryName: '金属废料和碎屑加工处理',
        pid: '421',
        label: '金属废料和碎屑加工处理（4210）',
      },
    ],
  },
  {
    value: '422',
    label: '非金属废料和碎屑加工处理',
    children: [
      {
        industryCode: '4220',
        industryName: '非金属废料和碎屑加工处理',
        pid: '422',
        label: '非金属废料和碎屑加工处理（4220）',
      },
    ],
  },
  {
    value: '431',
    label: '金属制品修理',
    children: [
      {
        industryCode: '4310',
        industryName: '金属制品修理',
        pid: '431',
        label: '金属制品修理（4310）',
      },
    ],
  },
  {
    value: '432',
    label: '通用设备修理',
    children: [
      {
        industryCode: '4320',
        industryName: '通用设备修理',
        pid: '432',
        label: '通用设备修理（4320）',
      },
    ],
  },
  {
    value: '433',
    label: '专用设备修理',
    children: [
      {
        industryCode: '4330',
        industryName: '专用设备修理',
        pid: '433',
        label: '专用设备修理（4330）',
      },
    ],
  },
  {
    value: '434',
    label: '铁路、船舶、航空航天等运输设备修理',
    children: [
      {
        industryCode: '4341',
        industryName: '铁路运输设备修理',
        pid: '434',
        label: '铁路运输设备修理（4341）',
      },
      {
        industryCode: '4342',
        industryName: '船舶修理',
        pid: '434',
        label: '船舶修理（4342）',
      },
      {
        industryCode: '4343',
        industryName: '航空航天器修理',
        pid: '434',
        label: '航空航天器修理（4343）',
      },
      {
        industryCode: '4349',
        industryName: '其他运输设备修理',
        pid: '434',
        label: '其他运输设备修理（4349）',
      },
    ],
  },
  {
    value: '435',
    label: '电气设备修理',
    children: [
      {
        industryCode: '4350',
        industryName: '电气设备修理',
        pid: '435',
        label: '电气设备修理（4350）',
      },
    ],
  },
  {
    value: '436',
    label: '仪器仪表修理',
    children: [
      {
        industryCode: '4360',
        industryName: '仪器仪表修理',
        pid: '436',
        label: '仪器仪表修理（4360）',
      },
    ],
  },
  {
    value: '439',
    label: '其他机械和设备修理业',
    children: [
      {
        industryCode: '4390',
        industryName: '其他机械和设备修理业',
        pid: '439',
        label: '其他机械和设备修理业（4390）',
      },
    ],
  },
]

export function getIndustryLabel(code: string): string | undefined {
  for (const group of INDUSTRY_GROUPS) {
    const industry = group.children.find(item => item.industryCode === code)
    if (industry) return industry.label
  }

  return undefined
}
